services:
  rust_devcontainer:
    image: toy-tcp
    build:
      context: .
    restart: always
    tty: true
    # プロセスを clone するときに特権プロセスでないとエラーになるために追加
    privileged: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
