[package]
name = "tcp-from-nic"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "=0.29.0", features=["socket", "net", "ioctl"] }
crossbeam-channel = "=0.5.13"
tracing = "=0.1.40"
tracing-subscriber = "=0.3.18"
bitflags = "=2.6.0"
