services:
  rust_devcontainer:
    image: rust:latest
    restart: always
    tty: true
    # プロセスを clone するときに特権プロセスでないとエラーになるために追加
    privileged: true
    volumes:
      - ../:/workspace
      # cgroup がデフォルトだと read-only になっているために追加
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    working_dir: /workspace
